"""LaTeX export utilities for generating exam and solution files."""

import os
from datetime import datetime
from pathlib import Path
from typing import Optional

from models import Exam


def export_exam_to_latex(exam: Exam, output_path: str) -> None:
    """
    Export an exam to a LaTeX file.
    
    Args:
        exam: The Exam object to export
        output_path: Path where the LaTeX file should be written
    """
    # Ensure output directory exists
    output_dir = Path(output_path).parent
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate LaTeX content
    latex_content = _generate_exam_latex(exam)
    
    # Write to file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(latex_content)


def export_solutions_to_latex(exam: Exam, output_path: str) -> None:
    """
    Export exam solutions to a LaTeX file.
    
    Args:
        exam: The Exam object containing solutions
        output_path: Path where the LaTeX file should be written
    """
    # Ensure output directory exists
    output_dir = Path(output_path).parent
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate LaTeX content
    latex_content = _generate_solutions_latex(exam)
    
    # Write to file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(latex_content)


def _generate_exam_latex(exam: Exam) -> str:
    """Generate LaTeX content for an exam (without solutions)."""
    timestamp_str = exam.timestamp.strftime("%Y-%m-%d %H:%M:%S")
    
    latex = "\\documentclass[11pt]{article}\n"
    latex += "\\usepackage[utf8]{inputenc}\n"
    latex += "\\usepackage{amsmath}\n"
    latex += "\\usepackage{amssymb}\n"
    latex += "\\usepackage{geometry}\n"
    latex += "\\geometry{margin=1in}\n"
    latex += "\n"
    latex += "\\title{Mock Exam}\n"
    latex += f"\\date{{{timestamp_str}}}\n"
    latex += "\\author{Generated by Mock Exam Generator}\n"
    latex += "\n"
    latex += "\\begin{document}\n"
    latex += "\\maketitle\n"
    latex += "\n"
    latex += "\\section*{Instructions}\n"
    latex += "Answer all questions. Show your work.\n"
    latex += "\n"
    
    for idx, question in enumerate(exam.questions, start=1):
        latex += f"\\section*{{Question {idx}}}\n"
        latex += f"\\textbf{{Topic:}} {question.topic}\n\n"
        latex += question.text
        latex += "\n\n"
        latex += "\\vspace{0.5cm}\n"
        latex += "\\hrule\n"
        latex += "\\vspace{0.5cm}\n\n"
    
    latex += "\\end{document}\n"
    
    return latex


def _generate_solutions_latex(exam: Exam) -> str:
    """Generate LaTeX content for exam solutions."""
    timestamp_str = exam.timestamp.strftime("%Y-%m-%d %H:%M:%S")
    
    latex = "\\documentclass[11pt]{article}\n"
    latex += "\\usepackage[utf8]{inputenc}\n"
    latex += "\\usepackage{amsmath}\n"
    latex += "\\usepackage{amssymb}\n"
    latex += "\\usepackage{geometry}\n"
    latex += "\\geometry{margin=1in}\n"
    latex += "\n"
    latex += "\\title{Solutions}\n"
    latex += f"\\date{{{timestamp_str}}}\n"
    latex += "\\author{Generated by Mock Exam Generator}\n"
    latex += "\n"
    latex += "\\begin{document}\n"
    latex += "\\maketitle\n"
    latex += "\n"
    latex += "\\section*{Solutions}\n"
    latex += "\n"
    
    for idx, question in enumerate(exam.questions, start=1):
        latex += f"\\section*{{Solution {idx}}}\n"
        latex += f"\\textbf{{Topic:}} {question.topic}\n\n"
        latex += "\\textbf{Problem:}\n\n"
        latex += question.text
        latex += "\n\n"
        latex += "\\textbf{Solution:}\n\n"
        latex += question.solution
        latex += "\n\n"
        latex += "\\vspace{0.5cm}\n"
        latex += "\\hrule\n"
        latex += "\\vspace{0.5cm}\n\n"
    
    latex += "\\end{document}\n"
    
    return latex

